// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file StringMsg.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _IDL_MSGS_IDL_STRINGMSG_H_
#define _IDL_MSGS_IDL_STRINGMSG_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(StringMsg_SOURCE)
#define StringMsg_DllAPI __declspec( dllexport )
#else
#define StringMsg_DllAPI __declspec( dllimport )
#endif // StringMsg_SOURCE
#else
#define StringMsg_DllAPI
#endif
#else
#define StringMsg_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

namespace idl_msgs
{
    namespace idl
    {
        /*!
         * @brief This class represents the structure StringMsg defined by the user in the IDL file.
         * @ingroup STRINGMSG
         */
        class StringMsg
        {
        public:

            /*!
             * @brief Default constructor.
             */
            eProsima_user_DllExport StringMsg();

            /*!
             * @brief Default destructor.
             */
            eProsima_user_DllExport virtual ~StringMsg();

            /*!
             * @brief Copy constructor.
             * @param x Reference to the object idl_msgs::idl::StringMsg that will be copied.
             */
            eProsima_user_DllExport StringMsg(const StringMsg &x);

            /*!
             * @brief Move constructor.
             * @param x Reference to the object idl_msgs::idl::StringMsg that will be copied.
             */
            eProsima_user_DllExport StringMsg(StringMsg &&x);

            /*!
             * @brief Copy assignment.
             * @param x Reference to the object idl_msgs::idl::StringMsg that will be copied.
             */
            eProsima_user_DllExport StringMsg& operator=(const StringMsg &x);

            /*!
             * @brief Move assignment.
             * @param x Reference to the object idl_msgs::idl::StringMsg that will be copied.
             */
            eProsima_user_DllExport StringMsg& operator=(StringMsg &&x);

            /*!
             * @brief This function copies the value in member var_string
             * @param _var_string New value to be copied in member var_string
             */
            eProsima_user_DllExport void var_string(const std::string &_var_string);

            /*!
             * @brief This function moves the value in member var_string
             * @param _var_string New value to be moved in member var_string
             */
            eProsima_user_DllExport void var_string(std::string &&_var_string);

            /*!
             * @brief This function returns a constant reference to member var_string
             * @return Constant reference to member var_string
             */
            eProsima_user_DllExport const std::string& var_string() const;

            /*!
             * @brief This function returns a reference to member var_string
             * @return Reference to member var_string
             */
            eProsima_user_DllExport std::string& var_string();

            /*!
             * @brief This function returns the maximum serialized size of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

            /*!
             * @brief This function returns the serialized size of a data depending on the buffer alignment.
             * @param data Data which is calculated its serialized size.
             * @param current_alignment Buffer alignment.
             * @return Serialized size.
             */
            eProsima_user_DllExport static size_t getCdrSerializedSize(const idl_msgs::idl::StringMsg& data, size_t current_alignment = 0);


            /*!
             * @brief This function serializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

            /*!
             * @brief This function deserializes an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



            /*!
             * @brief This function returns the maximum serialized size of the Key of an object
             * depending on the buffer alignment.
             * @param current_alignment Buffer alignment.
             * @return Maximum serialized size.
             */
            eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

            /*!
             * @brief This function tells you if the Key has been defined for this type
             */
            eProsima_user_DllExport static bool isKeyDefined();

            /*!
             * @brief This function serializes the key members of an object using CDR serialization.
             * @param cdr CDR serialization object.
             */
            eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

        private:
            std::string m_var_string;
        };
    }
}

#endif // _IDL_MSGS_IDL_STRINGMSG_H_